site_name: IVio
docs_dir: docs
nav:
  - index.md
  - C++ API-Reference:
    - formats.md
  - Python:
    - python-bindings.md
use_directory_urls: false
theme:
  name: readthedocs
  custom_dir: docs/readthedocs-customization
  highlightjs: true
  collapse_navigation: false
  locale: en
  prev_next_buttons_location: none
extra_javascript:
  - extra-highlights.js
plugins:
  - include-markdown:
      comments: false
      trailing_newlines: false
markdown_extensions:
  - tables
#  - admonition
#  - codehilite:
#      use_pygments: true
#  - toc:
#      permalink: true
#      separator: "_"
#  - sane_lists
#  - smarty
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - attr_list
#  - pymdownx.snippets
#  - pymdownx.superfences
#  - pymdownx.critic
#  - pymdownx.caret
#  - pymdownx.keys
#  - pymdownx.mark
#  - pymdownx.tilde
